#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
common模块，包含通用工具和函数
"""

from .file_utils import (
    create_folders,
    ensure_directory_exists,
    extract_pure_mod_name,
    move_to_complete,
    safe_copy_file,
    safe_move_file,
    rename_mod_folders,
    restore_backup,
    open_directory,
    contains_chinese_in_src,
    find_src_folders,
    create_jar_folder_in_mod,
    get_mapping_source,
    read_mod_info,
    load_mapping_rules,
)
from .report_utils import (
    generate_report,
    save_report,
    update_report_status,
    get_report_summary,
)
from .timestamp_utils import (
    get_timestamp,
    get_formatted_timestamp,
    get_date,
    get_time,
)
from .jar_utils import (
    is_jar_file,
    decompile_jar,
    get_decompiler_path,
)
from .tree_sitter_utils import (
    extract_ast_mappings,
    extract_strings_from_file,
    get_parser,
    initialize_languages,
)
from .yaml_utils import (
    load_yaml_mappings,
    save_yaml_mappings,
    generate_initial_yaml_mappings,
    apply_yaml_mapping,
    create_yaml_mapping_from_directory,
    update_yaml_mapping,
    YAMLMappingValidator,
    RuleConflictDetector,
    compare_yaml_versions,
    merge_yaml_versions,
    list_yaml_versions,
    restore_yaml_version,
    extract_mappings_from_processed_folder,
    update_mapping_status,
    merge_mapping_rules,
)
# 临时禁用以下模块，优先完成核心功能开发
# from .levenshtein_utils import (
#     calculate_similarity,
#     get_fuzzy_suggestions,
#     get_contextual_suggestions,
#     get_combined_suggestions,
#     find_best_match,
#     LevenshteinDistance,
# )
# from .suggestion_generator import SuggestionGenerator, generate_suggestions_for_yaml_file, create_localization_db_from_directory
# from .tools_integrator import ToolsIntegrator
from .logger_utils import (
    setup_logger, 
    get_logger, 
    log_exception, 
    log_progress, 
    log_result,
    log_error,
    log_warning,
    log_info,
    log_debug,
    set_log_level,
    get_error_code,
    log_entry_exit,
    setup_global_logging,
    ErrorCode,
    LogLevel,
    LoggerConfig,
    LoggerManager,
)
from .language_utils import (
    get_supported_languages,
    get_language_by_code,
    get_language_by_name,
    get_language_by_folder_name,
    get_default_language,
    get_language_folders,
    get_main_directories,
    is_supported_language,
    add_language,
    remove_language,
    save_language_config,
)
from .language_resource import (
    get_resource,
    set_resource,
    save_resource,
    add_language_resource,
    remove_language_resource,
    load_resource,
    load_all_resources,
)
from .language_context import (
    get_current_language,
    get_current_language_info,
    set_language,
    reset_to_default_language,
)

__all__ = [
    "file_utils",
    "create_folders",
    "ensure_directory_exists",
    "move_to_complete",
    "safe_copy_file",
    "safe_move_file",
    "rename_mod_folders",
    "restore_backup",
    "open_directory",
    "contains_chinese_in_src",
    "find_src_folders",
    "create_jar_folder_in_mod",
    "get_mapping_source",
    "read_mod_info",
    "load_mapping_rules",
    "report_utils",
    "generate_report",
    "save_report",
    "update_report_status",
    "get_report_summary",
    "timestamp_utils",
    "get_timestamp",
    "get_formatted_timestamp",
    "get_date",
    "get_time",
    "decompile_utils",
    "is_jar_file",
    "decompile_jar",
    "get_decompiler_path",
    "tree_sitter_utils",
    "extract_ast_mappings",
    "extract_strings_from_file",
    "get_parser",
    "initialize_languages",
    "yaml_utils",
    "load_yaml_mappings",
    "save_yaml_mappings",
    "generate_initial_yaml_mappings",
    "apply_yaml_mapping",
    "create_yaml_mapping_from_directory",
    "update_yaml_mapping",
    "YAMLMappingValidator",
    "RuleConflictDetector",
    "compare_yaml_versions",
    "merge_yaml_versions",
    "list_yaml_versions",
    "restore_yaml_version",
    "extract_mappings_from_processed_folder",
    "update_mapping_status",
    "merge_mapping_rules",
    "logger_utils",
    "setup_logger",
    "get_logger",
    "log_exception",
    "log_progress",
    "log_result",
    "log_error",
    "log_warning",
    "log_info",
    "log_debug",
    "set_log_level",
    "get_error_code",
    "log_entry_exit",
    "setup_global_logging",
    "ErrorCode",
    "LogLevel",
    "LoggerConfig",
    "LoggerManager",
    # 语言管理相关功能
    "language_utils",
    "get_supported_languages",
    "get_language_by_code",
    "get_language_by_name",
    "get_language_by_folder_name",
    "get_default_language",
    "get_language_folders",
    "get_main_directories",
    "is_supported_language",
    "add_language",
    "remove_language",
    "save_language_config",
    # 语言资源相关功能
    "language_resource",
    "get_resource",
    "set_resource",
    "save_resource",
    "add_language_resource",
    "remove_language_resource",
    "load_resource",
    "load_all_resources",
    # 语言上下文相关功能
    "language_context",
    "get_current_language",
    "get_current_language_info",
    "set_language",
    "reset_to_default_language",
]
